name: xramile
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  geocoding: ^2.1.1
  flutter_local_notifications: ^16.3.1
  fluttertoast: ^8.2.4
  http: ^1.2.0
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/lottie/
